version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: dependencias 
          command: bundle install
          
       - run:
          name: Compilar sitio 
          command: bundle exec jekyll build 
          
      - run:
          name: Imprime fecha 
          command: date
